services:
  oauth-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oauth-frontend-prod  # Cambié el nombre para coincidir con nginx config
    # ports:  # ⚠️ QUITAR - No necesitas exponer puertos, el proxy se encarga
    #   - "4200:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
    networks:
      - proxy-network  # ⚠️ CAMBIO IMPORTANTE: Usar la red del proxy

networks:
  proxy-network:  # ⚠️ CAMBIO: Conectar a la red externa del proxy
    external: true